version = 0.1

[default.global.parameters]
stack_name = "sam-hello-world"
region = "ap-northeast-2"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "sam-hello-world"
profile = "test-secret-key"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "/Users/changhyun-lee/Desktop/sam-hello-world/template.yaml"
dependency_layer = false

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
